# Generated by Django 3.2.13 on 2023-04-19 16:20

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    if getattr(settings, 'TESTING_MIGRATIONS', False):
        dependencies = [
            ('eox_nelp', '0001_initial'),
        ]
        course_overview_model = 'eox_nelp.courseoverview'
    else:
        dependencies = [
            ('course_overviews', '0025_auto_20210702_1602'),
            ('eox_nelp', '0001_initial'),
        ]
        course_overview_model = 'course_overviews.courseoverview'

    operations = [
        migrations.CreateModel(
            name='UpcomingCourseDueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('notification_date', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=course_overview_model)),
            ],
            options={
                'unique_together': {('course_id', 'location_id', 'notification_date')},
            },
        ),
    ]
