# Generated by Django 3.2.19 on 2023-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcourse',
            name='public',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackunit',
            name='public',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
