# Generated by Django 3.2.13 on 2023-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0004_feedback_public_default_to_false'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cdtrans_lms_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cdtrans_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('cdtrans_username', models.CharField(blank=True, max_length=200, null=True)),
                ('cdtrans_email', models.CharField(blank=True, max_length=100, null=True)),
                ('cdtrans_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('cdtrans_course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cdtrans_enrollment_id', models.IntegerField(blank=True, null=True)),
                ('cdtrans_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('cdtrans_cert_status', models.CharField(blank=True, max_length=100, null=True)),
                ('cdtrans_date', models.DateTimeField(blank=True, null=True)),
                ('cdtrans_response_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cdtrans_status', models.CharField(blank=True, max_length=100, null=True)),
                ('cdtrans_ecom_order_id', models.IntegerField(blank=True, null=True)),
                ('cdtrans_ecom_payment_reponse_id', models.IntegerField(blank=True, null=True)),
                ('cdtrans_extra_data_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('cdtrans_extra_data_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('cdtrans_extra_data_3', models.CharField(blank=True, max_length=1000, null=True)),
                ('cdtrans_extra_data_4', models.TextField(blank=True, null=True)),
                ('show_msg_case0', models.BooleanField(blank=True, help_text='Not ready', null=True)),
                ('show_msg_case1', models.BooleanField(blank=True, help_text='Not ready', null=True)),
                ('show_msg_case2', models.BooleanField(blank=True, help_text='Not ready', null=True)),
                ('show_trans_info', models.BooleanField(blank=True, help_text='Not ready', null=True)),
                ('show_msg_custom', models.BooleanField(blank=True, help_text='Not ready', null=True)),
                ('custom_msg', models.TextField(blank=True, help_text='Not ready', null=True)),
                ('call_to_action_1_msg', models.CharField(blank=True, help_text='Not ready', max_length=1000, null=True)),
                ('call_to_action_2_msg', models.CharField(blank=True, help_text='Not ready', max_length=1000, null=True)),
                ('call_to_action_3_msg', models.CharField(blank=True, help_text='Not ready', max_length=1000, null=True)),
                ('call_to_action_1_url', models.CharField(blank=True, help_text='Not ready', max_length=1000, null=True)),
                ('call_to_action_2_url', models.CharField(blank=True, help_text='Not ready', max_length=1000, null=True)),
                ('call_to_action_3_url', models.CharField(blank=True, help_text='Not ready', max_length=1000, null=True)),
                ('redirect_from_dashboard', models.BooleanField(blank=True, help_text='Not ready', null=True)),
                ('redirect_from_course', models.BooleanField(blank=True, help_text='Not ready', null=True)),
                ('redirect_from_certificate', models.BooleanField(blank=True, help_text='Not ready', null=True)),
                ('redirect_from_everywhere', models.BooleanField(blank=True, help_text='Not ready', null=True)),
                ('internal_status', models.CharField(choices=[('case_0', 'case_0'), ('case_1', 'case_1'), ('case_2', 'case_2'), ('pending_manual_eval', 'pending_manual_eval'), ('other_case', 'other_case'), ('ignore', 'ignore'), ('resolution_by_case_0', 'resolution_by_case_0'), ('resolution_by_case_1', 'resolution_by_case_1'), ('resolution_by_case_2', 'resolution_by_case_2'), ('resolution_other', 'resolution_other')], default='case_0', max_length=30)),
                ('internal_notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('internal_view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
