# Generated by Django 3.2.21 on 2024-05-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0006_auto_20230726_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='PearsonRTENModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('resultNotification', 'Result Notification'), ('placeHold', 'Place Hold'), ('releaseHold', 'Release Hold'), ('modifyResultStatus', 'Modify Result Status'), ('revokeResult', 'Revoke Result'), ('unrevokeResult', 'Unrevoke Result')], max_length=20)),
            ],
        ),
    ]
