# Generated by Django 3.2.21 on 2024-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0006_auto_20230726_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='call_to_action_1_msg',
            field=models.CharField(blank=True, help_text='Name of the button for case 1', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='call_to_action_1_url',
            field=models.CharField(blank=True, help_text='Link of the button for case 1', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='call_to_action_2_msg',
            field=models.CharField(blank=True, help_text='Name of the button for case 2', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='call_to_action_2_url',
            field=models.CharField(blank=True, help_text='Link of the button for case 2', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='call_to_action_3_msg',
            field=models.CharField(blank=True, help_text='Name of the button at the end of the message', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='call_to_action_3_url',
            field=models.CharField(blank=True, help_text='Link of the button at the end of the message', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='custom_msg',
            field=models.TextField(blank=True, help_text='Use a "lang-ar" or "lang-en" class to select language', null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='show_msg_case0',
            field=models.BooleanField(blank=True, help_text='Will show the case 0 msg to the user', null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='show_msg_case1',
            field=models.BooleanField(blank=True, help_text='Will show the case 1 msg to the user', null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='show_msg_case2',
            field=models.BooleanField(blank=True, help_text='Will show the case 2 msg to the user', null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='show_msg_custom',
            field=models.BooleanField(blank=True, help_text='Will show the following html to the user', null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='show_trans_info',
            field=models.BooleanField(blank=True, help_text='Will show the transaction details to the user', null=True),
        ),
    ]
