# Generated by Django 3.2.21 on 2024-05-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0007_auto_20240529_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='PearsonRTENModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('result-notification', 'Result Notification'), ('place-hold', 'Place Hold'), ('release-hold', 'Release Hold'), ('modify-result-status', 'Modify Result Status'), ('revoke-result', 'Revoke Result'), ('unrevoke-result', 'Unrevoke Result')], max_length=20)),
            ],
        ),
    ]
