# Generated by Django 3.2.21 on 2024-07-05 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eox_nelp', '0009_pearsonrtenevent_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pearsonrtenevent',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
