# Generated by Django 3.2.21 on 2024-07-08 17:29

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0027_auto_20221102_1109'),
        ('eox_nelp', '0010_pearsonrtenevent_candidate'),
    ]

    if getattr(settings, 'TESTING_MIGRATIONS', False):
        dependencies = [
            ('eox_nelp', '0010_pearsonrtenevent_candidate'),
        ]
        course_overview_model = 'eox_nelp.courseoverview'
    else:
        dependencies = [
            ('eox_nelp', '0010_pearsonrtenevent_candidate'),
            ('course_overviews', '0025_auto_20210702_1602'),
        ]
        course_overview_model = 'course_overviews.courseoverview'

    operations = [
        migrations.AddField(
            model_name='pearsonrtenevent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=course_overview_model),
        ),
    ]
