# Generated by Django 4.0.10 on 2025-03-10 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eox_nelp', '0012_add_pearson_engines_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(help_text='Group code related the cert. Normally mapped to course_id', max_length=50)),
                ('certificate_id', models.CharField(help_text='Unique identifier for the certificate.', max_length=50)),
                ('certificate_url_en', models.URLField(help_text='URL for the certificate in English.', max_length=500)),
                ('certificate_url_ar', models.URLField(help_text='URL for the certificate in Arabic.', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the certificate was created.')),
                ('user', models.ForeignKey(help_text='The user associated with this certificate.', on_delete=django.db.models.deletion.CASCADE, related_name='external_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Certificate',
                'verbose_name_plural': 'External Certificates',
            },
        ),
    ]
