# Generated by Django 4.0.10 on 2025-02-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0012_add_pearson_engines_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PearsonRTENEvent',
        ),
    ]
