# Generated by Django 4.0.10 on 2025-03-15 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    if getattr(settings, 'TESTING_MIGRATIONS', False):
        dependencies = [
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
            ('eox_nelp', '0013_delete_pearsonrtenevent'),
        ]
        course_overview_model = 'eox_nelp.courseoverview'
    else:
        dependencies = [
            ('course_overviews', '0029_alter_historicalcourseoverview_options'),
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
            ('eox_nelp', '0013_delete_pearsonrtenevent'),
        ]
        course_overview_model = 'course_overviews.courseoverview'

    operations = [
        migrations.CreateModel(
            name='ExternalCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(help_text='Unique identifier for the certificate.', max_length=50)),
                ('certificate_url_en', models.URLField(help_text='URL for the certificate in English.', max_length=500)),
                ('certificate_url_ar', models.URLField(help_text='URL for the certificate in Arabic.', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the certificate was created.')),
                ('course_overview', models.ForeignKey(help_text='The course overview associated with this certificate.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=course_overview_model)),
                ('user', models.ForeignKey(help_text='The user associated with this certificate.', on_delete=django.db.models.deletion.CASCADE, related_name='external_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Certificate',
                'verbose_name_plural': 'External Certificates',
            },
        ),
    ]
