# Generated by Django 4.0.10 on 2025-05-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0014_add_external_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcourse',
            name='reason',
            field=models.CharField(blank=True, choices=[('IC', 'Inappropriate content'), ('GV', 'Graphic violence'), ('HA', 'Hateful or abusive content'), ('CI', 'Copycat or impersonation'), ('OO', 'Other objection')], default=None, max_length=2, null=True),
        ),
    ]
